### ISSUE TITLE
Handle case where can't ssh into node in nodeSetup

### ISSUE THREAD

**Issue by matthewsucar** [NCAR/HPCFL_CloudBursting#31]
Maybe destroy and recreate the instance?

**Comment by Will-Shanks** [comment]
Eventually the scheduler will notice this node wasn't ever setup and mark it as down. This will then cause the node to be destroyed the next time `add` or `rm` are called. Retrying creating the instance is tricky, because if it takes too long the scheduler will mark the node as down anyway.
